services:
  nuxt-app:
    build: .
    container_name: frontend-tests
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:3002:3000"
