services:
  vite-static:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-test-vite
    ports:
      - "127.0.0.1:18081:80"
    restart: unless-stopped
    networks:
      - stellar_app-network

networks:
  stellar_app-network:
    external: true
    name: stellar_app-network
